name: Build iOS App
on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: client

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install kivy-ios
        
    - name: Install Homebrew dependencies
      run: |
        brew install autoconf automake libtool pkg-config
        brew link libtool
        
    - name: Build iOS app
      run: |
        cd src
        toolchain build kivy
        toolchain create TournamentApp main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: TournamentApp-ios
        path: client/src/TournamentApp-ios
