name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Cache Homebrew
      uses: actions/cache@v3
      with:
        path: /usr/local/Homebrew
        key: brew-${{ runner.os }}

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}

    - name: Cache kivy-ios downloads
      uses: actions/cache@v3
      with:
        path: kivy-ios/downloads
        key: downloads-${{ runner.os }}

    - name: Install dependencies
      run: |
        brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer autoconf automake libtool
        python -m pip install --upgrade pip
        pip install kivy requests kivy-ios

    - name: List available recipes
      run: |
        toolchain recipes

    - name: Build Kivy iOS recipes
      run: |
        toolchain build python3 kivy

    - name: Create iOS build
      run: |
        mkdir ios-build
        cd ios-build
        toolchain create TournamentApp ../TournamentApp/src/main.py
        toolchain build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ios-build/
